### ISSUE TITLE
Better handling of forks

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#100]
Create subsection of `project` for fork info rather than duplicating entries.

**Comment by JrGoodle** [comment]
# Proposed Syntax

```yaml
groups:
    - name: llvm
      projects:
        - name: llvm-mirror/llvm
          path: llvm
    - name: clang
      projects:
        - name: llvm-mirror/clang
          path: llvm/tools/clang
          remote: upstream
          forks:
            - name: jrgoodle/clang
              path: llvm/tools/clang
              remote: origin
```
