### ISSUE TITLE
Add ability to create hooks

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#523]
They can be stored in the clowder repo under `hooks/`. Think about places where it makes sense to run them.

Some possibilities:
- pre-herd
- post-herd
- pre-reset
- post-reset
- pre-checkout
- post-checkout
- pre-stash
- post-stash
- pre-start
- post-start
- pre-clean
- post-clean
- pre-prune
- post-prune

**Comment by JrGoodle** [comment]
could allow specifying in yaml file, something like:

```
hooks:
  herd:
    before: something
    after: something_else
  status:
    before: something
    after: something_else
```
