### ISSUE TITLE
Change sources section formatting

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#583]
```yaml
sources:
  - name: chromium
    url: chromium.googlesource.com
    protocol: https
  - name: sourceforge
    url: git.code.sf.net
    protocol: https
```

```yaml
sources:
  chromium:
    url: chromium.googlesource.com
    protocol: https
  sourceforge:
    url: git.code.sf.net
    protocol: https
```
