### ISSUE TITLE
Add upstream option

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#586]
Like a fork, but reversed. Allows user's fork to be specified as the project. Can infer remote to be `upstream`

```yaml
projects:
  - name: JrGoodle/schemastore
    upstream:
      name: SchemaStore/schemastore
```
