### ISSUE TITLE
Update submodules syntax

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#602]
```
submodules: true
```

```
submodules:
  recursive: true
```

**Comment by JrGoodle** [comment]
## option 1

```yaml
project:
  git:
    submodules: true
```

```yaml
project:
  git:
    submodules: recursive
```

## option 2

```yaml
project:
  git:
    submodules: true
```

```yaml
project:
  git:
    submodules:
      recursive: true
```

## option 3

```yaml
project:
  git:
    submodule:
      update: true
```

```yaml
project:
  git:
    submodule:
      update:
        recursive: true
```

This form would leave open these possibilities:

```yaml
project:
  git:
    submodule:
      update:
```

```yaml
project:
  git:
    submodule:
      update:
       recursive:
```

## option 4

```yaml
project:
  git:
    submodule:
      update: true
      recursive: true
```
