### ISSUE TITLE
Add command to update yaml with submodules

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#604]
Might make sense under `yaml` command:

```bash
clowder yaml update submodules
```

Add submodules to project:

```yaml
- name: something
  submodules:
    my_submodule:
      name: someplace/my_submodule  
      path: somewhere
      branch: some_branch
      source: some_source
```
