### ISSUE TITLE
Add env to projects

### ISSUE THREAD

**Issue by JrGoodle** [JrGoodle/clowder#610]
Allow custom environment variables to be specified in clowder.yml for the `clowder forall` command.

See: https://gerrit.googlesource.com/git-repo/+/master/docs/manifest-format.md#element-annotation

Possible names: `env`, `environment`

```yaml
projects:
  myproject:
    name: 'myname/myproject'
    env:
      VARIABLE_NAME: 'variable_value'
```
